AWSTemplateFormatVersion: '2010-09-09'
Description: A template to deploy the cloudfront distribution with S3 as origin (to be used with aws cli)

#Create a Cloudfront distribution adding the S3 bucket as origin

Resources:
  MyDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        ViewerCertificate:
          AcmCertificateArn: !Ref MyCertificate
          SslSupportMethod: sni-only
        Aliases:
          - engineerhammoud.com
        DefaultCacheBehavior:
          ViewerProtocolPolicy: allow-all #Or use: redirect-to-https
          TargetOriginId: alihammoudresume.s3-website-us-east-1.amazonaws.com
          DefaultTTL: 0
          MinTTL: 0
          MaxTTL: 0
          ForwardedValues:
            QueryString: false 
        Origins:
          - DomainName: alihammoudresume.s3-website-us-east-1.amazonaws.com
            Id: alihammoudresume.s3-website-us-east-1.amazonaws.com
            CustomOriginConfig:
              OriginProtocolPolicy: match-viewer
        Enabled: "true"
        DefaultRootObject: index.html

#Create an SSL certificate for the site using ACM

  MyCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: engineerhammoud.com
      ValidationMethod: DNS
      SubjectAlternativeNames: 
        - www.engineerhammoud.com

#Create an alias record in Route53 which points to the domain name for the Cloudfront distribution

  MyRoute53Record:
    Type: "AWS::Route53::RecordSetGroup"
    Properties:
      HostedZoneId: Z0648573ONKBNEMEB47Z
      RecordSets:
        - Name: engineerhammoud.com
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2  #Hardcoded for Cloudfront
            DNSName: !GetAtt MyDistribution.DomainName
        