AWSTemplateFormatVersion: '2010-09-09'
Description: A template to deploy DynamoDB and create a table to save the counter information (to be used with aws cli)

#Create a Cloudfront distribution adding the S3 bucket as origin

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AliVisitorCount
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"